# Configuracion basica del Microservicio
spring.application.name=msvc-web-semantica
server.port=8084

# =========================================================
# CONFIGURACION DE APACHE JENA FUSEKI (Obligatorio)
# =========================================================
# Estas son las variables que causaban el error al arrancar
# Asegurate de que el nombre 'atencion_medica' sea el que creaste en Fuseki
jena.fuseki.query-url=http://localhost:3030/atencion_medica/query
jena.fuseki.update-url=http://localhost:3030/atencion_medica/update

# =========================================================
# CONFIGURACION DE BASE DE DATOS (Opcional)
# =========================================================
# Solo usa esto si tienes entidades @Entity de JPA en este msvc.
# Si solo usas Web Semantica, puedes comentar estas lineas.
spring.datasource.url=jdbc:postgresql://localhost:5432/msvc_web_semantica
spring.datasource.username=postgres
spring.datasource.password=666999
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================================================
# CONFIGURACION DE LOGS (Para ver que hace Jena)
# =========================================================
logging.level.org.springcloud.nova.ing.atencion.medica.msvc.web.semantica=DEBUG
logging.level.org.apache.jena=INFO