spring.application.name=msvc-paciente

spring.datasource.url=jdbc:postgresql://localhost:5432/msvc_pacientes
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8083
